services:
  dbt-doc-to-pdf:
    build: .
    volumes:
      - ${TARGET_DIR:-./sample_project/target}:/target:ro
      - ./output:/output
    environment:
      OUTPUT: /output/catalog.pdf
      PROJECT: ${PROJECT:-sample_project}
